version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5

    restart: unless-stopped

  nats:
    image: nats-streaming
    command: -js -sd /data
    depends_on:
      - postgres
    volumes:
      - nats:/data
    ports:
      - 4222:4222
    healthcheck:
      test: ["CMD", "nats-server", "--help"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  migrations:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - nats
      - postgres
    entrypoint: [ "/bin/sh", "/migrations/entrypoint.sh" ]

  myapp:
    build: .
    depends_on:
      - postgres
      - nats
      - migrations
    ports:
      - 8080:8080
    healthcheck:
      test: curl --fail http://localhost:8080/order/b563feb7b2b84b6test|| exit 1
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

volumes:
  postgres:
  migrations:
  nats:


