version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    restart: unless-stopped

  nats:
    image: nats-streaming
    command: -js -sd /data
    depends_on:
      - postgres
    volumes:
      - nats:/data
    ports:
      - 4222:4222

  migrations:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - nats
      - postgres
    entrypoint: [ "/bin/sh", "/migrations/entrypoint.sh" ]

  myapp:
    build: .
    depends_on:
      - postgres
      - nats
      - migrations
    ports:
      - 8080:8080

volumes:
  postgres:
  migrations:
  nats:

