-- DROP TABLE IF EXISTS items;

-- DROP TABLE IF EXISTS deliveries;

-- DROP TABLE IF EXISTS payments;

-- DROP TABLE IF EXISTS orders;




TRUNCATE TABLE items CASCADE;

TRUNCATE TABLE deliveries CASCADE;

TRUNCATE TABLE payments CASCADE;

TRUNCATE TABLE orders CASCADE;